### PR TITLE
NH-80074 Otelcol: Add lambda distro version to resource attribute

### PR DESCRIPTION
**Pull request by jerrytfleung**
- Added `sw.apm.otelcol.version` in resource attributes processor to indicating current opentelemetry-lambda distro.
- Fixed an unit test case

[NH-80243](https://swicloud.atlassian.net/browse/NH-80243)

[NH-80243]: https://swicloud.atlassian.net/browse/NH-80243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by cheempz — COMMENTED** [review]
LGTM! One ask--you mentioned the pitfall of forgetting update this. Can it be checked for in the publish workflow, or mentioned in the release process?

**Comment by jerrytfleung** [comment]
> LGTM! One ask--you mentioned the pitfall of forgetting update this. Can it be checked for in the publish workflow, or mentioned in the release process?

The check won't have much benefit as I still need to do the following manual action.
1. Remove the tag
2. Bump the version in config.yaml
3. Tag again to release

Not prefer to pollute the workflow because of inspecting the content of config.yaml.

**Comment by cheempz** [comment]
How about adding a RELEASE markdown to our branch under the `collector` directory with some info then?

**Comment by jerrytfleung** [comment]
> How about adding a RELEASE markdown to our branch under the `collector` directory with some info then?

I wonder how does a RELEASE markdown file help. Sound like I have to maintain config.yaml and RELEASE together.

**Comment by cheempz** [comment]
> > How about adding a RELEASE markdown to our branch under the `collector` directory with some info then?
> 
> I wonder how does a RELEASE markdown file help. Sound like I have to maintain config.yaml and RELEASE together.

it would help someone new to this know what the steps are for releasing our otelcol extension layers.

**Comment by jerrytfleung** [comment]
> > > How about adding a RELEASE markdown to our branch under the `collector` directory with some info then?
> > 
> > 
> > I wonder how does a RELEASE markdown file help. Sound like I have to maintain config.yaml and RELEASE together.
> 
> it would help someone new to this know what the steps are for releasing our otelcol extension layers.

I changed to do it in another way.

1. Extracting the version from the tags
2. Replace the placeholder string by the version in config.yaml
3. build and publish the lambda

As the version is set to config.yaml only, I think it is okay not to commit that file to the tag. That `sw.apm.otelcol.version` field doesn't hurt to investigate issue in the future.

**Review by cheempz — APPROVED** [review]
Much better system, putting automation to work!

**Pull request merged**
