### PR TITLE
NH-76996 - Fixed time parsing in Python JSON log format

### PR DESCRIPTION
**Pull request by jerrytfleung**
Fixed parsing this timestamp string `2024-07-05T21:12:37Z`

[NH-76996](https://swicloud.atlassian.net/browse/NH-76996)

[NH-76996]: https://swicloud.atlassian.net/browse/NH-76996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by cleverchuk — APPROVED** [review]
LTGM. Although for java, it's possible for users to change the timestamp format for their log line using the config file of their chosen logging framework

**Comment by jerrytfleung** [comment]
@cleverchuk & I can see different format can be found in AWS lambda JAVA. 
e.g.
`19:30:53.609 [main] DEBUG software.amazon.awssdk.http.apache.internal.net.SdkSslSocket - closing s3.us-east-1.amazonaws.com/52.216.48.72:443`

The pattern is not rigid in https://logging.apache.org/log4j/2.x/manual/layouts.html#PatternLayout.

I think a better and reasonable way to handle this problem could be documenting our supported time format in Java APM lambda. i.e. [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339). It is standard Internet timestamp. @cleverchuk also agree during our huddle. 

@cheempz What do you think?

**Comment by cheempz** [comment]
@jerrytfleung @cleverchuk sure, let's go with documenting as a first approach. Would be great if we can provide example dateformat config snippet that the customer can copypaste into their logging config.

It seems currently we'd log an ERROR level message per parse failure (and just omit turning the Telemetry API event into a LogRecord)? That would be logged since default for extension is WARN level and burn up the customer's CW logs usage. How about reduce the log level, and we'd want to highlight the invalid format parsing consequence aka no logs in documentation.

**Comment by jerrytfleung** [comment]
> Although for java, it's possible for users to change the timestamp format for their log line using the config file of their chosen logging framework

@cheempz What log level do you prefer?
I am thinking not taking parse failure as an error (i.e. returning empty Log), keep parsing other fields and export a log record

**Comment by jerrytfleung** [comment]
> @jerrytfleung @cleverchuk sure, let's go with documenting as a first approach. Would be great if we can provide example dateformat config snippet that the customer can copypaste into their logging config.
> 
> It seems currently we'd log an ERROR level message per parse failure (and just omit turning the Telemetry API event into a LogRecord)? That would be logged since default for extension is WARN level and burn up the customer's CW logs usage. How about reduce the log level, and we'd want to highlight the invalid format parsing consequence aka no logs in documentation.

@cheempz What log level do you prefer?
I am thinking not taking parse failure as an error (i.e. returning empty Log), keep parsing other fields and export a log record

**Comment by cheempz** [comment]
Good thought, this is the [time_unix_nano](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/logs/v1/logs.proto#L139-L140) right? Seems we can set 0 in the case of parse failure, and in this case I'd say the extension should log a DEBUG level message.

**Comment by jerrytfleung** [comment]
> time_unix_nano

Yes, 

I was thinking not setting the timestamp field. 

DEBUG looks good to me. I will create a PR for that

**Comment by jerrytfleung** [comment]
> > time_unix_nano
> 
> Yes,
> 
> I was thinking not setting the timestamp field.
> 
> DEBUG looks good to me. I will create a PR for that

After testing, I found out that I will set the timestamp from the AWS top level log event's timestamp. I think it is reasonable.

**Pull request merged**
